[versions]
kotlin = "2.2.20"
kotlinx-serialization = "1.9.0"
ktor = "3.1.0"
xmlunit = "2.10.0"
maven-publish = "0.28.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.10.1" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
xmlunit-core = { module = "org.xmlunit:xmlunit-core", version.ref = "xmlunit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
